---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-chase.fullname" . }}
  labels:
    {{- include "kafka-chase.labels" . | nindent 4 }}
data:
  serviceconfig.yaml: |
    {{- include "kafka-chase.config" . | nindent 4 }}
